package com.xfusion.fusiondesk.repository;
import com.xfusion.fusiondesk.exception.DatabaseException;import com.xfusion.fusiondesk.model.*;import com.xfusion.fusiondesk.service.LlmFailoverPolicy;import java.sql.*;import java.time.Instant;import java.util.Optional;
public class LlmProviderStateRepository{
 private final DatabaseManager database;public LlmProviderStateRepository(DatabaseManager database){this.database=database;}
 public void ensureDefault(Connection c)throws SQLException{if(find(c).isEmpty())insertDefault(c);}
 public LlmProviderState get(){try(Connection c=database.openConnection()){return find(c).orElse(defaultState());}catch(SQLException e){throw new DatabaseException("Failed to read LLM provider state",e);}}
 public boolean claimPrimaryProbe(Instant now,LlmFailoverPolicy policy){return database.inTransaction(c->{LlmProviderState s=find(c).orElse(defaultState());if(s.state()==LlmCircuitState.CLOSED)return true;if(s.nextRetryAt()!=null&&s.nextRetryAt().isAfter(now))return false;try(PreparedStatement ps=c.prepareStatement("UPDATE llm_provider_state SET state='HALF_OPEN',next_retry_at=?,version=version+1 WHERE id=1 AND version=?")){database.bindInstant(ps,1,now.plus(policy.retryInterval()));ps.setLong(2,s.version());return ps.executeUpdate()==1;}});}
 public void recordFailure(String model,String error,Instant now,LlmFailoverPolicy policy){database.inTransaction(c->{LlmProviderState s=find(c).orElse(null);if(s==null){insertDefault(c);s=find(c).orElseThrow();}int failures=s.consecutiveFailures()+1;LlmCircuitState state=failures>=policy.failureThreshold()?LlmCircuitState.OPEN:LlmCircuitState.CLOSED;try(PreparedStatement ps=c.prepareStatement("UPDATE llm_provider_state SET state=?,consecutive_failures=?,consecutive_successes=0,last_failure_at=?,next_retry_at=?,current_model=?,last_error=?,version=version+1 WHERE id=1")){ps.setString(1,state.name());ps.setInt(2,failures);database.bindInstant(ps,3,now);if(state==LlmCircuitState.OPEN)database.bindInstant(ps,4,now.plus(policy.retryInterval()));else ps.setNull(4,Types.TIMESTAMP);ps.setString(5,model);ps.setString(6,truncate(error));ps.executeUpdate();}return null;});}
 public void recordSuccess(String model,Instant now,LlmFailoverPolicy policy){database.inTransaction(c->{LlmProviderState s=find(c).orElse(null);if(s==null){insertDefault(c);s=find(c).orElseThrow();}int successes=s.consecutiveSuccesses()+1;boolean recovered=successes>=policy.successThreshold();try(PreparedStatement ps=c.prepareStatement("UPDATE llm_provider_state SET state=?,consecutive_failures=0,consecutive_successes=?,last_success_at=?,next_retry_at=?,current_model=?,last_error=NULL,version=version+1 WHERE id=1")){ps.setString(1,recovered?"CLOSED":"HALF_OPEN");ps.setInt(2,recovered?0:successes);database.bindInstant(ps,3,now);if(recovered)ps.setNull(4,Types.TIMESTAMP);else database.bindInstant(ps,4,now.plus(policy.retryInterval()));ps.setString(5,model);ps.executeUpdate();}return null;});}
 public void recordFallbackUse(String model){database.inTransaction(c->{try(PreparedStatement ps=c.prepareStatement("UPDATE llm_provider_state SET current_model=?,version=version+1 WHERE id=1")){ps.setString(1,model);ps.executeUpdate();}return null;});}
 private Optional<LlmProviderState> find(Connection c)throws SQLException{try(PreparedStatement ps=c.prepareStatement("SELECT state,consecutive_failures,consecutive_successes,last_failure_at,next_retry_at,last_success_at,current_model,last_error,version FROM llm_provider_state WHERE id=1");ResultSet rs=ps.executeQuery()){return rs.next()?Optional.of(new LlmProviderState(LlmCircuitState.valueOf(rs.getString(1)),rs.getInt(2),rs.getInt(3),database.readInstant(rs,"last_failure_at"),database.readInstant(rs,"next_retry_at"),database.readInstant(rs,"last_success_at"),rs.getString(7),rs.getString(8),rs.getLong(9))):Optional.empty();}}
 private void insertDefault(Connection c)throws SQLException{try(PreparedStatement ps=c.prepareStatement("INSERT INTO llm_provider_state(id,state,consecutive_failures,consecutive_successes,version) VALUES(1,'CLOSED',0,0,0)")){ps.executeUpdate();}}
 private LlmProviderState defaultState(){return new LlmProviderState(LlmCircuitState.CLOSED,0,0,null,null,null,null,null,0);}
 private String truncate(String value){if(value==null)return "LLM failure";return value.substring(0,Math.min(900,value.length()));}
}
