package com.xfusion.fusiondesk.repository;
import java.sql.*;import java.time.Instant;import java.util.*;
final class MySqlDialect implements DatabaseDialect {
    private static final Calendar UTC=Calendar.getInstance(TimeZone.getTimeZone("UTC"));
    public DatabaseType type(){return DatabaseType.MYSQL;}public void configure(Connection c){}public void bindInstant(PreparedStatement ps,int i,Instant v)throws SQLException{ps.setTimestamp(i,Timestamp.from(v),UTC);}public Instant readInstant(ResultSet rs,String c)throws SQLException{Timestamp v=rs.getTimestamp(c,UTC);return v==null?null:v.toInstant();}public String metadataKeyColumn(){return "meta_key";}
    public List<String> schemaStatements(){return List.of(
        "CREATE TABLE IF NOT EXISTS tickets (id BIGINT NOT NULL AUTO_INCREMENT,title VARCHAR(200) NOT NULL,description TEXT NOT NULL,submitter VARCHAR(100) NOT NULL,status VARCHAR(32) NOT NULL,category VARCHAR(64) NULL,priority VARCHAR(8) NOT NULL,version BIGINT NOT NULL DEFAULT 0,dedup_key CHAR(64) NOT NULL,active_dedup_key CHAR(64) GENERATED ALWAYS AS (CASE WHEN status <> 'CLOSED' THEN dedup_key ELSE NULL END) STORED,created_at DATETIME(3) NOT NULL,updated_at DATETIME(3) NOT NULL,PRIMARY KEY(id),UNIQUE KEY uq_tickets_active_dedup(active_dedup_key),KEY idx_tickets_status(status),KEY idx_tickets_category_priority(category,priority),KEY idx_tickets_submitter(submitter),KEY idx_tickets_created_at(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS ai_suggestions (id BIGINT NOT NULL AUTO_INCREMENT,ticket_id BIGINT NOT NULL,suggested_category VARCHAR(64) NOT NULL,suggested_priority VARCHAR(8) NOT NULL,summary VARCHAR(500) NOT NULL,reason VARCHAR(1000) NOT NULL,raw_response TEXT NOT NULL,model VARCHAR(128) NOT NULL,prompt_version VARCHAR(64) NOT NULL,status VARCHAR(32) NOT NULL,final_category VARCHAR(64) NULL,final_priority VARCHAR(8) NULL,created_at DATETIME(3) NOT NULL,reviewed_at DATETIME(3) NULL,PRIMARY KEY(id),CONSTRAINT fk_ai_suggestion_ticket FOREIGN KEY(ticket_id) REFERENCES tickets(id),KEY idx_ai_suggestions_ticket(ticket_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS audit_events (id BIGINT NOT NULL AUTO_INCREMENT,ticket_id BIGINT NOT NULL,event_type VARCHAR(64) NOT NULL,before_data TEXT NULL,after_data TEXT NULL,created_at DATETIME(3) NOT NULL,PRIMARY KEY(id),CONSTRAINT fk_audit_ticket FOREIGN KEY(ticket_id) REFERENCES tickets(id),KEY idx_audit_ticket_time(ticket_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS evaluation_runs (id BIGINT NOT NULL AUTO_INCREMENT,prompt_version VARCHAR(64) NOT NULL,model VARCHAR(128) NOT NULL,total_cases INT NOT NULL,normal_cases INT NOT NULL,adversarial_cases INT NOT NULL,schema_valid_rate DECIMAL(8,4) NOT NULL,category_accuracy DECIMAL(8,4) NOT NULL,priority_accuracy DECIMAL(8,4) NOT NULL,exact_match_rate DECIMAL(8,4) NOT NULL,injection_resistance_rate DECIMAL(8,4) NOT NULL,created_at DATETIME(3) NOT NULL,PRIMARY KEY(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS evaluation_case_results (id BIGINT NOT NULL AUTO_INCREMENT,run_id BIGINT NOT NULL,case_id VARCHAR(128) NOT NULL,expected_category VARCHAR(64) NOT NULL,predicted_category VARCHAR(64) NULL,expected_priority VARCHAR(8) NOT NULL,predicted_priority VARCHAR(8) NULL,schema_valid BOOLEAN NOT NULL,category_correct BOOLEAN NOT NULL,priority_correct BOOLEAN NOT NULL,exact_match BOOLEAN NOT NULL,adversarial BOOLEAN NOT NULL,injection_passed BOOLEAN NULL,summary VARCHAR(500) NULL,reason VARCHAR(1000) NULL,error_message VARCHAR(1000) NULL,PRIMARY KEY(id),CONSTRAINT fk_eval_case_run FOREIGN KEY(run_id) REFERENCES evaluation_runs(id) ON DELETE CASCADE,KEY idx_eval_case_run(run_id),KEY idx_eval_case_case_id(case_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS prompt_versions (id BIGINT NOT NULL AUTO_INCREMENT,version VARCHAR(64) NOT NULL,system_prompt LONGTEXT NOT NULL,user_prompt_template LONGTEXT NOT NULL,status VARCHAR(32) NOT NULL,active_marker TINYINT GENERATED ALWAYS AS (CASE WHEN status='ACTIVE' THEN 1 ELSE NULL END) STORED,source_model VARCHAR(128) NULL,positive_samples INT NOT NULL DEFAULT 0,negative_samples INT NOT NULL DEFAULT 0,modified_samples INT NOT NULL DEFAULT 0,baseline_exact_match DECIMAL(8,4) NULL,candidate_exact_match DECIMAL(8,4) NULL,baseline_category_accuracy DECIMAL(8,4) NULL,candidate_category_accuracy DECIMAL(8,4) NULL,baseline_priority_accuracy DECIMAL(8,4) NULL,candidate_priority_accuracy DECIMAL(8,4) NULL,baseline_schema_valid_rate DECIMAL(8,4) NULL,candidate_schema_valid_rate DECIMAL(8,4) NULL,baseline_injection_rate DECIMAL(8,4) NULL,candidate_injection_rate DECIMAL(8,4) NULL,created_at DATETIME(3) NOT NULL,activated_at DATETIME(3) NULL,PRIMARY KEY(id),UNIQUE KEY uq_prompt_version(version),UNIQUE KEY uq_prompt_active(active_marker),KEY idx_prompt_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS prompt_optimization_runs (id BIGINT NOT NULL AUTO_INCREMENT,source_prompt_id BIGINT NOT NULL,candidate_prompt_id BIGINT NULL,before_evaluation_run_id BIGINT NULL,after_evaluation_run_id BIGINT NULL,positive_samples INT NOT NULL,negative_samples INT NOT NULL,modified_samples INT NOT NULL,status VARCHAR(32) NOT NULL,decision_reason VARCHAR(1000) NULL,created_at DATETIME(3) NOT NULL,finished_at DATETIME(3) NULL,PRIMARY KEY(id),CONSTRAINT fk_opt_source_prompt FOREIGN KEY(source_prompt_id) REFERENCES prompt_versions(id),CONSTRAINT fk_opt_candidate_prompt FOREIGN KEY(candidate_prompt_id) REFERENCES prompt_versions(id),CONSTRAINT fk_opt_before_eval FOREIGN KEY(before_evaluation_run_id) REFERENCES evaluation_runs(id),CONSTRAINT fk_opt_after_eval FOREIGN KEY(after_evaluation_run_id) REFERENCES evaluation_runs(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS prompt_training_samples (id BIGINT NOT NULL AUTO_INCREMENT,optimization_run_id BIGINT NOT NULL,suggestion_id BIGINT NOT NULL,label VARCHAR(32) NOT NULL,expected_category VARCHAR(64) NULL,expected_priority VARCHAR(8) NULL,created_at DATETIME(3) NOT NULL,PRIMARY KEY(id),CONSTRAINT fk_sample_run FOREIGN KEY(optimization_run_id) REFERENCES prompt_optimization_runs(id) ON DELETE CASCADE,CONSTRAINT fk_sample_suggestion FOREIGN KEY(suggestion_id) REFERENCES ai_suggestions(id),UNIQUE KEY uq_prompt_sample(optimization_run_id,suggestion_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS app_metadata (meta_key VARCHAR(128) PRIMARY KEY,value VARCHAR(500) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");}
}
