package com.xfusion.fusiondesk.repository;

import com.xfusion.fusiondesk.ai.PromptBuilder;
import com.xfusion.fusiondesk.evaluation.EvaluationMetrics;
import com.xfusion.fusiondesk.exception.DatabaseException;
import com.xfusion.fusiondesk.model.*;
import java.sql.*;import java.time.Instant;import java.util.*;

public class PromptVersionRepository {
    private final DatabaseManager database;
    public PromptVersionRepository(DatabaseManager database){this.database=database;}

    public void ensureDefault(Connection c)throws SQLException{
        PromptBuilder builder=new PromptBuilder();boolean hasActive;try(PreparedStatement q=c.prepareStatement("SELECT 1 FROM prompt_versions WHERE status='ACTIVE' LIMIT 1");ResultSet rs=q.executeQuery()){hasActive=rs.next();}
        ensureBuiltIn(c,"baseline-v0",builder.systemPromptBaseline(),builder.userPromptTemplateBaseline(),PromptStatus.RETIRED);
        ensureBuiltIn(c,"v1",builder.systemPromptV1(),builder.userPromptTemplateV1(),PromptStatus.RETIRED);
        ensureBuiltIn(c,"v2",builder.systemPromptV2(),builder.userPromptTemplateV1(),PromptStatus.RETIRED);
        ensureBuiltIn(c,"v3",builder.systemPrompt(),builder.userPromptTemplate(),hasActive?PromptStatus.RETIRED:PromptStatus.ACTIVE);
        try(PreparedStatement ps=c.prepareStatement("UPDATE prompt_versions SET user_prompt_template=? WHERE version IN ('v1','v2') AND (user_prompt_template IS NULL OR user_prompt_template='')")){ps.setString(1,builder.userPromptTemplateV1());ps.executeUpdate();}
        try(PreparedStatement ps=c.prepareStatement("UPDATE prompt_versions SET user_prompt_template=? WHERE version='v3' AND (user_prompt_template IS NULL OR user_prompt_template='')")){ps.setString(1,builder.userPromptTemplate());ps.executeUpdate();}
    }
    private void ensureBuiltIn(Connection c,String version,String system,String user,PromptStatus status)throws SQLException{try(PreparedStatement q=c.prepareStatement("SELECT 1 FROM prompt_versions WHERE version=?")){q.setString(1,version);try(ResultSet rs=q.executeQuery()){if(rs.next())return;}}Instant now=Instant.now();try(PreparedStatement ps=c.prepareStatement("INSERT INTO prompt_versions(version,system_prompt,user_prompt_template,status,source_model,created_at,activated_at) VALUES(?,?,?,?,NULL,?,?)")){ps.setString(1,version);ps.setString(2,system);ps.setString(3,user);ps.setString(4,status.name());database.bindInstant(ps,5,now);if(status==PromptStatus.ACTIVE)database.bindInstant(ps,6,now);else ps.setNull(6,Types.TIMESTAMP);ps.executeUpdate();}}
    public PromptVersion findActive(){try(Connection c=database.openConnection()){return findActive(c);}catch(SQLException e){throw new DatabaseException("Failed to read active prompt",e);}}
    public PromptVersion findActive(Connection c)throws SQLException{try(PreparedStatement ps=c.prepareStatement("SELECT id,version,system_prompt,user_prompt_template,status,source_model,created_at,activated_at FROM prompt_versions WHERE status='ACTIVE' ORDER BY id DESC LIMIT 1");ResultSet rs=ps.executeQuery()){if(!rs.next())throw new DatabaseException("No active prompt is configured.",null);return map(rs);}}
    public List<PromptTrainingSample> findReviewedSamples(){String sql="SELECT s.id,t.title,t.description,s.status,s.suggested_category,s.suggested_priority,s.final_category,s.final_priority FROM ai_suggestions s JOIN tickets t ON t.id=s.ticket_id WHERE s.status IN ('CONFIRMED','MODIFIED','REJECTED') ORDER BY s.id";try(Connection c=database.openConnection();PreparedStatement ps=c.prepareStatement(sql);ResultSet rs=ps.executeQuery()){List<PromptTrainingSample> out=new ArrayList<>();while(rs.next()){SuggestionStatus status=SuggestionStatus.valueOf(rs.getString("status"));String fc=rs.getString("final_category"),fp=rs.getString("final_priority");out.add(new PromptTrainingSample(rs.getLong("id"),status==SuggestionStatus.CONFIRMED?"POSITIVE":status.name(),rs.getString("title"),rs.getString("description"),TicketCategory.valueOf(rs.getString("suggested_category")),TicketPriority.valueOf(rs.getString("suggested_priority")),fc==null?null:TicketCategory.valueOf(fc),fp==null?null:TicketPriority.valueOf(fp)));}return out;}catch(SQLException e){throw new DatabaseException("Failed to load prompt training samples",e);}}
    public long createRun(PromptVersion source,List<PromptTrainingSample> samples,int positive,int negative,int modified){return database.inTransaction(c->{Instant now=Instant.now();long id;try(PreparedStatement ps=c.prepareStatement("INSERT INTO prompt_optimization_runs(source_prompt_id,positive_samples,negative_samples,modified_samples,status,created_at) VALUES(?,?,?,?,'RUNNING',?)",Statement.RETURN_GENERATED_KEYS)){ps.setLong(1,source.id());ps.setInt(2,positive);ps.setInt(3,negative);ps.setInt(4,modified);database.bindInstant(ps,5,now);ps.executeUpdate();try(ResultSet keys=ps.getGeneratedKeys()){keys.next();id=keys.getLong(1);}}for(PromptTrainingSample s:samples)try(PreparedStatement ps=c.prepareStatement("INSERT INTO prompt_training_samples(optimization_run_id,suggestion_id,label,expected_category,expected_priority,created_at) VALUES(?,?,?,?,?,?)")){ps.setLong(1,id);ps.setLong(2,s.suggestionId());ps.setString(3,s.label());if(s.expectedCategory()==null)ps.setNull(4,Types.VARCHAR);else ps.setString(4,s.expectedCategory().name());if(s.expectedPriority()==null)ps.setNull(5,Types.VARCHAR);else ps.setString(5,s.expectedPriority().name());database.bindInstant(ps,6,now);ps.executeUpdate();}return id;});}
    public PromptVersion insertCandidate(long runId,String version,String prompt,String model,int positive,int negative,int modified){return database.inTransaction(c->{Instant now=Instant.now();String userTemplate=new PromptBuilder().userPromptTemplate();long id;try(PreparedStatement ps=c.prepareStatement("INSERT INTO prompt_versions(version,system_prompt,user_prompt_template,status,source_model,positive_samples,negative_samples,modified_samples,created_at) VALUES(?,?,?,'CANDIDATE',?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS)){ps.setString(1,version);ps.setString(2,prompt);ps.setString(3,userTemplate);ps.setString(4,model);ps.setInt(5,positive);ps.setInt(6,negative);ps.setInt(7,modified);database.bindInstant(ps,8,now);ps.executeUpdate();try(ResultSet keys=ps.getGeneratedKeys()){keys.next();id=keys.getLong(1);}}try(PreparedStatement ps=c.prepareStatement("UPDATE prompt_optimization_runs SET candidate_prompt_id=? WHERE id=?")){ps.setLong(1,id);ps.setLong(2,runId);ps.executeUpdate();}return new PromptVersion(id,version,prompt,userTemplate,PromptStatus.CANDIDATE,model,now,null);});}
    public void finish(long runId,PromptVersion source,PromptVersion candidate,long beforeRunId,long afterRunId,EvaluationMetrics before,EvaluationMetrics after,boolean promote,String reason){database.inTransaction(c->{Instant now=Instant.now();String metrics="baseline_exact_match=?,candidate_exact_match=?,baseline_category_accuracy=?,candidate_category_accuracy=?,baseline_priority_accuracy=?,candidate_priority_accuracy=?,baseline_schema_valid_rate=?,candidate_schema_valid_rate=?,baseline_injection_rate=?,candidate_injection_rate=?";try(PreparedStatement ps=c.prepareStatement("UPDATE prompt_versions SET "+metrics+",status=? WHERE id=?")){bindMetrics(ps,before,after);ps.setString(11,promote?"CANDIDATE":"REJECTED");ps.setLong(12,candidate.id());ps.executeUpdate();}if(promote){try(PreparedStatement ps=c.prepareStatement("UPDATE prompt_versions SET status='RETIRED' WHERE id=? AND status='ACTIVE'")){ps.setLong(1,source.id());ps.executeUpdate();}try(PreparedStatement ps=c.prepareStatement("UPDATE prompt_versions SET status='ACTIVE',activated_at=? WHERE id=? AND status='CANDIDATE'")){database.bindInstant(ps,1,now);ps.setLong(2,candidate.id());if(ps.executeUpdate()!=1)throw new SQLException("Candidate prompt could not be activated");}}try(PreparedStatement ps=c.prepareStatement("UPDATE prompt_optimization_runs SET before_evaluation_run_id=?,after_evaluation_run_id=?,status=?,decision_reason=?,finished_at=? WHERE id=?")){ps.setLong(1,beforeRunId);ps.setLong(2,afterRunId);ps.setString(3,promote?"PROMOTED":"REJECTED");ps.setString(4,reason);database.bindInstant(ps,5,now);ps.setLong(6,runId);ps.executeUpdate();}return null;});}
    public void fail(long runId,String reason){database.inTransaction(c->{try(PreparedStatement ps=c.prepareStatement("UPDATE prompt_versions SET status='REJECTED' WHERE status='CANDIDATE' AND id=(SELECT candidate_prompt_id FROM prompt_optimization_runs WHERE id=?)")){ps.setLong(1,runId);ps.executeUpdate();}try(PreparedStatement ps=c.prepareStatement("UPDATE prompt_optimization_runs SET status='FAILED',decision_reason=?,finished_at=? WHERE id=?")){ps.setString(1,reason);database.bindInstant(ps,2,Instant.now());ps.setLong(3,runId);ps.executeUpdate();}return null;});}
    private void bindMetrics(PreparedStatement ps,EvaluationMetrics b,EvaluationMetrics a)throws SQLException{ps.setDouble(1,b.exactMatchRate()/100);ps.setDouble(2,a.exactMatchRate()/100);ps.setDouble(3,b.categoryAccuracy()/100);ps.setDouble(4,a.categoryAccuracy()/100);ps.setDouble(5,b.priorityAccuracy()/100);ps.setDouble(6,a.priorityAccuracy()/100);ps.setDouble(7,b.schemaValidRate()/100);ps.setDouble(8,a.schemaValidRate()/100);ps.setDouble(9,b.injectionResistanceRate()/100);ps.setDouble(10,a.injectionResistanceRate()/100);}
    private PromptVersion map(ResultSet rs)throws SQLException{return new PromptVersion(rs.getLong("id"),rs.getString("version"),rs.getString("system_prompt"),rs.getString("user_prompt_template"),PromptStatus.valueOf(rs.getString("status")),rs.getString("source_model"),database.readInstant(rs,"created_at"),database.readInstant(rs,"activated_at"));}
}
