package com.xfusion.fusiondesk.repository;
import java.sql.*;import java.time.Instant;import java.util.List;
final class SqliteDialect implements DatabaseDialect {
    public DatabaseType type(){return DatabaseType.SQLITE;}public void configure(Connection c)throws SQLException{try(Statement s=c.createStatement()){s.execute("PRAGMA foreign_keys = ON");s.execute("PRAGMA busy_timeout = 5000");s.execute("PRAGMA journal_mode = WAL");}}
    public void bindInstant(PreparedStatement ps,int i,Instant v)throws SQLException{ps.setString(i,v.toString());}public Instant readInstant(ResultSet rs,String c)throws SQLException{String v=rs.getString(c);return v==null?null:Instant.parse(v);}public String metadataKeyColumn(){return "key";}
    public List<String> schemaStatements(){return List.of(
        "CREATE TABLE IF NOT EXISTS tickets (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,description TEXT NOT NULL,submitter TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('NEW','IN_PROGRESS','RESOLVED','CLOSED')),category TEXT CHECK(category IS NULL OR category IN ('ACCOUNT_ACCESS','SOFTWARE_FAILURE','NETWORK','HARDWARE_OFFICE','BUSINESS_SYSTEM','OTHER')),priority TEXT NOT NULL CHECK(priority IN ('P0','P1','P2','P3')),version INTEGER NOT NULL DEFAULT 0 CHECK(version>=0),dedup_key TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)",
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_tickets_active_dedup ON tickets(dedup_key) WHERE status <> 'CLOSED'","CREATE INDEX IF NOT EXISTS idx_tickets_status ON tickets(status)","CREATE INDEX IF NOT EXISTS idx_tickets_category_priority ON tickets(category,priority)","CREATE INDEX IF NOT EXISTS idx_tickets_submitter ON tickets(submitter)","CREATE INDEX IF NOT EXISTS idx_tickets_created_at ON tickets(created_at)",
        "CREATE TABLE IF NOT EXISTS audit_events (id INTEGER PRIMARY KEY AUTOINCREMENT,ticket_id INTEGER NOT NULL,event_type TEXT NOT NULL,before_data TEXT,after_data TEXT,created_at TEXT NOT NULL,FOREIGN KEY(ticket_id) REFERENCES tickets(id))","CREATE INDEX IF NOT EXISTS idx_audit_ticket_time ON audit_events(ticket_id,created_at)",
        "CREATE TABLE IF NOT EXISTS ai_suggestions (id INTEGER PRIMARY KEY AUTOINCREMENT,ticket_id INTEGER NOT NULL,suggested_category TEXT NOT NULL CHECK(suggested_category IN ('ACCOUNT_ACCESS','SOFTWARE_FAILURE','NETWORK','HARDWARE_OFFICE','BUSINESS_SYSTEM','OTHER')),suggested_priority TEXT NOT NULL CHECK(suggested_priority IN ('P0','P1','P2','P3')),summary TEXT NOT NULL,reason TEXT NOT NULL,raw_response TEXT NOT NULL,model TEXT NOT NULL,prompt_version TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('PENDING','CONFIRMED','MODIFIED','REJECTED')),final_category TEXT,final_priority TEXT,created_at TEXT NOT NULL,reviewed_at TEXT,FOREIGN KEY(ticket_id) REFERENCES tickets(id))","CREATE INDEX IF NOT EXISTS idx_ai_suggestions_ticket ON ai_suggestions(ticket_id,created_at)",
        "CREATE TABLE IF NOT EXISTS evaluation_runs (id INTEGER PRIMARY KEY AUTOINCREMENT,prompt_version TEXT NOT NULL,model TEXT NOT NULL,total_cases INTEGER NOT NULL,normal_cases INTEGER NOT NULL,adversarial_cases INTEGER NOT NULL,schema_valid_rate REAL NOT NULL,category_accuracy REAL NOT NULL,priority_accuracy REAL NOT NULL,exact_match_rate REAL NOT NULL,injection_resistance_rate REAL NOT NULL,created_at TEXT NOT NULL)",
        "CREATE TABLE IF NOT EXISTS evaluation_case_results (id INTEGER PRIMARY KEY AUTOINCREMENT,run_id INTEGER NOT NULL,case_id TEXT NOT NULL,expected_category TEXT NOT NULL,predicted_category TEXT,expected_priority TEXT NOT NULL,predicted_priority TEXT,schema_valid INTEGER NOT NULL,category_correct INTEGER NOT NULL,priority_correct INTEGER NOT NULL,exact_match INTEGER NOT NULL,adversarial INTEGER NOT NULL,injection_passed INTEGER,summary TEXT,reason TEXT,error_message TEXT,FOREIGN KEY(run_id) REFERENCES evaluation_runs(id) ON DELETE CASCADE)","CREATE INDEX IF NOT EXISTS idx_eval_case_run ON evaluation_case_results(run_id)","CREATE INDEX IF NOT EXISTS idx_eval_case_case_id ON evaluation_case_results(case_id)","CREATE TABLE IF NOT EXISTS app_metadata (key TEXT PRIMARY KEY,value TEXT NOT NULL)");}
}
